#!/bin/bash
set -e

echo "============================================="
echo "  Jenkins Pipeline Setup Script"
echo "============================================="

JENKINS_URL="http://localhost:8080"
CLI_JAR="/tmp/jenkins-cli.jar"

# Download Jenkins CLI if not present
if [ ! -f "$CLI_JAR" ]; then
    echo "Downloading Jenkins CLI..."
    curl -s "$JENKINS_URL/jnlpJars/jenkins-cli.jar" -o "$CLI_JAR"
fi

echo ""
echo "Step 1: Jenkins Credentials Setup"
echo "-----------------------------------"
echo "Please configure the following in Jenkins:"
echo ""
echo "1. Go to: $JENKINS_URL/credentials/store/system/domain/_/newCredentials"
echo "2. Add 'Username with password' credential:"
echo "   - ID: dockerhub-creds"
echo "   - Username: <your-dockerhub-username>"
echo "   - Password: <your-dockerhub-password-or-token>"
echo "   - Description: DockerHub Credentials"
echo ""
echo "3. Add 'Username with password' credential:"
echo "   - ID: github-creds"
echo "   - Username: <your-github-username>"
echo "   - Password: <your-github-pat>"
echo "   - Description: GitHub Credentials"
echo ""

echo "Step 2: Create Pipeline Job"
echo "-----------------------------------"
echo "1. Go to: $JENKINS_URL/newJob"
echo "2. Enter job name: java-cicd-pipeline"
echo "3. Select: 'Pipeline' and click OK"
echo "4. In the Pipeline section:"
echo "   - Definition: 'Pipeline script from SCM'"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/tholuchurivijaykumar/java-cicd-project.git"
echo "   - Branch: */main"
echo "   - Script Path: Jenkinsfile"
echo "5. Under 'Build Triggers', check 'Build periodically'"
echo "   - Schedule: H/2 * * * * (every 2 minutes)"
echo "6. Click Save"
echo "7. Click 'Build Now' to trigger the first build"
echo ""

echo "Step 3: Verify"
echo "-----------------------------------"
echo "Monitor pipeline at: $JENKINS_URL/job/java-cicd-pipeline/"
echo ""
echo "Pipeline stages:"
echo "  1. Checkout    - Pull code from GitHub"
echo "  2. Build       - Maven compile"
echo "  3. Unit Tests  - Maven test"
echo "  4. Package     - Maven package JAR"
echo "  5. Docker      - Build & push to DockerHub"
echo "  6. Deploy      - Deploy to Minikube"
echo "  7. Verify      - Check deployment status"
echo ""

echo "Step 4: Cron Job"
echo "-----------------------------------"
echo "The cron job is configured in the Jenkinsfile:"
echo "  Schedule: H/2 * * * *"
echo "  This triggers the pipeline every 2 minutes"
echo "  checking for SCM changes."
echo ""
echo "============================================="
echo "  Manual Setup Instructions Complete!"
echo "============================================="
